const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const TOOLS_SRC = path.join(__dirname, '../utilities');
const TOOLS_DIST = path.join(TOOLS_SRC, 'dist');
const STATIC_DIR = path.join(__dirname, '../static');
const STATIC_TOOLS_DIR = path.join(STATIC_DIR, 'utilities');
const PARTIALS_DIR = path.join(__dirname, '../layouts/partials');

// Ensure directories exist
if (!fs.existsSync(STATIC_TOOLS_DIR)) {
    fs.mkdirSync(STATIC_TOOLS_DIR, { recursive: true });
}

console.log('Building Tools submodule...');
try {
    // Install and Build Svelte App
    execSync('npm install', { cwd: TOOLS_SRC, stdio: 'inherit' });
    execSync('npm run build', { cwd: TOOLS_SRC, stdio: 'inherit' });

    // Move _app to static/utilities/_app
    const appSrc = path.join(TOOLS_DIST, '_app');
    const appDest = path.join(STATIC_TOOLS_DIR, '_app');
    
    // Clean old assets
    if (fs.existsSync(appDest)) {
        fs.rmSync(appDest, { recursive: true, force: true });
    }
    
    // Copy new assets
    if (fs.existsSync(appSrc)) {
         fs.renameSync(appSrc, appDest); // Move instead of copy to save space/time
         console.log('Moved _app to static/utilities/_app');
    } else {
        console.error('Error: _app directory not found in dist. Build might have failed or config is wrong.');
        process.exit(1);
    }

    // Process index.html to extract assets
    const indexHtmlPath = path.join(TOOLS_DIST, 'index.html');
    if (fs.existsSync(indexHtmlPath)) {
        let indexHtml = fs.readFileSync(indexHtmlPath, 'utf-8');
        
        // Extract link tags for CSS/ModulePreload
        const linkRegex = /<link[^>]+(?:stylesheet|modulepreload)[^>]+>/g;
        const links = indexHtml.match(linkRegex) || [];
        
        // Extract script tags (entry point)
        const scriptRegex = /<script\s+type="module"[^>]*>[\s\S]*?<\/script>/g;
        // Also catch external src scripts
        const scriptSrcRegex = /<script\s+type="module"\s+src=[^>]+><\/script>/g;
        // Extract inline script (SvelteKit bootstrapper)
        const inlineScriptRegex = /<script>\s*\{[\s\S]*?kit\.start[\s\S]*?\}\s*<\/script>/;

        const scripts = [
            ...(indexHtml.match(scriptRegex) || []),
            ...(indexHtml.match(scriptSrcRegex) || [])
        ];
        
        const inlineMatch = indexHtml.match(inlineScriptRegex);
        if (inlineMatch) {
            scripts.push(inlineMatch[0]);
        }

        // Combine into partial
        const partialContent = `
<!-- Auto-generated by scripts/build.js -->
${links.join('\n')}
${scripts.join('\n')}
`;
        fs.writeFileSync(path.join(PARTIALS_DIR, 'tools_assets.html'), partialContent);
        console.log('Generated tools_assets.html');

    } else {
         console.error('Error: index.html not found in dist.');
         process.exit(1);
    }

    console.log('Svelte integration complete.');

} catch (e) {
    console.error('Build failed:', e);
    process.exit(1);
}
